### ISSUE TITLE
Use `scipy` or `astropy` constants instead of hard-coded values

### ISSUE THREAD

**Issue by jwhite3** [cmagness/spectrAOD#1]
https://github.com/cmagness/spectrAOD/blob/aafdb3bb03ab5b5e4d064d973f265b8b344ac8ca/spectrAOD/format_data.py#L18

[scipy](https://docs.scipy.org/doc/scipy/reference/constants.html)

[astropy](http://docs.astropy.org/en/stable/constants/)

**Comment by cmagness** [comment]
also resolved in a commit
