### ISSUE TITLE
Can't append to a None type

### ISSUE THREAD

**Issue by jwhite3** [cmagness/spectrAOD#2]
https://github.com/cmagness/spectrAOD/blob/aafdb3bb03ab5b5e4d064d973f265b8b344ac8ca/spectrAOD/format_data.py#L72

If this is called without the `velocity` attribute being set as some sort of list first it'll break

**Comment by cmagness** [comment]
this was resolved by f407a6917e03d814ecdb7b11af6026e41440524c i believe
